if ( JMSD_CMAKE_DEPENDENCY_OUTPUT_IS_ON )
	message( STATUS "[JMSD] DEPENDENCY IS SET: ${PROJECT_NAME}_DEPENDENCY_DIRS: ${${PROJECT_NAME}_DEPENDENCY_DIRS}" )
	message( STATUS "[JMSD] DEPENDENCY IS SET: ${PROJECT_NAME}_DEFINITIONS: ${${PROJECT_NAME}_DEFINITIONS}" )
endif()
