include( ${JMSD_CMAKE_SETTINGS_PATH}/macroses/functions.cmake )

if ( JMSD_CMAKE_DEPENDENCY_OUTPUT_IS_ON )
	message( STATUS "[JMSD] Directory dependency: ${PROJECT_NAME}_DEPENDENCY_DIRS: " )
	JMSD_ECHO_DIRECTORY_LIST( ${PROJECT_NAME}_DEPENDENCY_DIRS )
	message( STATUS "[JMSD] Library dependency: ${PROJECT_NAME}_DEPENDENCY_LIBS: ${${PROJECT_NAME}_DEPENDENCY_LIBS}" )
	message( STATUS "[JMSD] Build dependency: ${PROJECT_NAME}_BUILD_DEFINITIONS: ${${PROJECT_NAME}_BUILD_DEFINITIONS}" )
	message( STATUS "[JMSD] Link dependency: ${PROJECT_NAME}_LINK_DEFINITIONS: ${${PROJECT_NAME}_LINK_DEFINITIONS}" )
endif()
