set( ${PROJECT_NAME}_DEPENDENCY_DIRS ${${PROJECT_NAME}_DEPENDENCY_DIRS_VAR} CACHE INTERNAL "[JMSD] ${PROJECT_NAME}_DEPENDENCY_DIRS" FORCE )
set( ${PROJECT_NAME}_BUILD_DEFINITIONS ${${PROJECT_NAME}_BUILD_DEFINITIONS} CACHE INTERNAL "[JMSD] ${PROJECT_NAME}_DEFINITIONS" FORCE )
set( ${PROJECT_NAME}_LINK_DEFINITIONS ${${PROJECT_NAME}_LINK_DEFINITIONS} CACHE INTERNAL "[JMSD] ${PROJECT_NAME}_DEFINITIONS" FORCE )

include( ${JMSD_CMAKE_SETTINGS_PATH}/verbosity/project-dependency-footer.cmake )
