include( ${JMSD_CMAKE_SETTINGS_PATH}/set-verbosity-configuration.cmake )

JMSD_CMAKE_CURRENT_FILE_IN( "set-target-directories.cmake" )

set( JMSD_DESTINATION_BINARIES_DIR __binaries )
set( JMSD_DESTINATION_LIBRARIES_DIR __libraries )

if ( QT_QMAKE_EXECUTABLE )
	set( CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${JMSD_DESTINATION_LIBRARIES_DIR} )
	set( CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${JMSD_DESTINATION_LIBRARIES_DIR} )
	set( CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${JMSD_DESTINATION_BINARIES_DIR} )
else()
	set( CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${JMSD_DESTINATION_LIBRARIES_DIR} )
	set( CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${JMSD_DESTINATION_LIBRARIES_DIR} )
	set( CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${JMSD_DESTINATION_BINARIES_DIR} )
endif()

JMSD_CMAKE_CURRENT_FILE_OUT( "set-target-directories.cmake" )
